// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIYKTE5iMo2pE-thB4fn0h68AiW-ce0eA',
    appId: '1:376343754528:web:248a3949df6d55c96a4945',
    messagingSenderId: '376343754528',
    projectId: 'psicapp-45e46',
    authDomain: 'psicapp-45e46.firebaseapp.com',
    storageBucket: 'psicapp-45e46.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjPDeVH8BD1IswVWNfnBNU9wrdz9tH6Ik',
    appId: '1:376343754528:android:c7101075e4020dab6a4945',
    messagingSenderId: '376343754528',
    projectId: 'psicapp-45e46',
    storageBucket: 'psicapp-45e46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT5vCr0qlw2N_Fq7RAcytL86elpT-RqI0',
    appId: '1:376343754528:ios:e2d912bf9ed5c8a86a4945',
    messagingSenderId: '376343754528',
    projectId: 'psicapp-45e46',
    storageBucket: 'psicapp-45e46.appspot.com',
    iosClientId: '376343754528-4mtckrmbcbduphkkgnl3l0nrkq8cg4vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.psciapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT5vCr0qlw2N_Fq7RAcytL86elpT-RqI0',
    appId: '1:376343754528:ios:d7ba19bcda833fa66a4945',
    messagingSenderId: '376343754528',
    projectId: 'psicapp-45e46',
    storageBucket: 'psicapp-45e46.appspot.com',
    iosClientId: '376343754528-f5rs8q4plajhlbb46m6v4t7e589o5vft.apps.googleusercontent.com',
    iosBundleId: 'com.example.psciapp.RunnerTests',
  );
}
